FROM elixir:1.5

MAINTAINER Geovane Fedrecheski <geonnave@gmail.com>

RUN mix local.hex --force
RUN mix archive.install --force https://github.com/phoenixframework/archives/raw/master/phx_new.ez

EXPOSE 5000

ADD . /app
WORKDIR /app